### ISSUE TITLE
ESL-002 <fix> Ajustes de segurança (Credenciais)

### ISSUE THREAD

**Issue by MrVitor0** [alexandreSouza31/Meu_Blog#2]
### Descrição
As credenciais do Firebase estão expostas no arquivo `/src/firebase/config.js`, o que é uma prática insegura. O objetivo deste issue é corrigir essa vulnerabilidade movendo as credenciais para um arquivo `.env`, protegendo-as de exposição indesejada.

### Tarefas
- [x] Remover as credenciais antigas do arquivo `/src/firebase/config.js`. **(Apague também no firebase, gere novas credenciais)**
- [x] Criar um novo arquivo `.env` para armazenar as credenciais do Firebase.
- [x] Configurar a aplicação para ler as credenciais do arquivo `.env`.
- [x] Verificar se a aplicação está funcionando corretamente após a mudança.

### Documentação
Para utilizar variáveis de ambiente (`.env`) no JavaScript, siga a documentação oficial do pacote `dotenv`:
[Documentação dotenv](https://www.npmjs.com/package/dotenv)

**Comment by alexandreSouza31** [comment]
Mudanças feitas. Muito obrigado pela sugestão, Victor Hugo!
